#  **************************************************************************  #
#                                                                              #
#                                                          :::      ::::::::   #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahabachi <ahabachi@student.1337.ma>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/12 14:58:50 by ahabachi          #+#    #+#              #
#    Updated: 2023/05/13 00:08:42 by ahabachi         ###   ########.fr        #
#                                                                              #
#  **************************************************************************  #
#                                                                              #
#   █████████            ██████████         ██████████         ██████████      #
#   ██     ██                    ██                 ██         ██      ██      #
#          ██                    ██                 ██         ██      ██      #
#          ██                    ██                 ██                 ██      #
#          ██            ██████████         ██████████                 ██      #
#          ██                    ██                 ██                 ██      #
#          ██                    ██                 ██                 ██      #
#          ██                    ██                 ██                 ██      #
#       ████████         ██████████         ██████████                 ██      #
#                                                                              #
#  **************************************************************************  #

version: "3.6"

networks:
    ahabachi-inception-network:
        name: ahabachi-inception-network

volumes:
    ahabachi-inception-wp-volume:
        name: ahabachi-inception-wp-volume
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${INCEPTION_WORDPRESS_VOLUME}
    ahabachi-inception-db-volume:
        name: ahabachi-inception-db-volume
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${INCEPTION_MARIADB_VOLUME}

services:
    mariadb:
        image: mariadb:ahabachi-inception
        container_name: mariadb
        build: requirements/mariadb
        env_file: .env
        networks:
            - ahabachi-inception-network
        volumes:
            -  ahabachi-inception-db-volume:/var/lib/mysql
        restart: on-failure
    wordpress:
        image: wordpress:ahabachi-inception
        container_name: wordpress
        build: requirements/wordpress
        volumes:
            - ahabachi-inception-wp-volume:/var/www/wordpress
        depends_on:
            - mariadb
        env_file: .env
        networks:
            - ahabachi-inception-network
        restart: on-failure
    nginx:
        image: nginx:ahabachi-inception
        container_name: nginx
        build: ./requirements/nginx
        ports:
            - ${INCEPTION_PORT}:${INCEPTION_PORT}
        environment:
            - INCEPTION_PORT=${INCEPTION_PORT}
            - INCEPTION_DOMAIN_NAME=${INCEPTION_DOMAIN_NAME}
        depends_on:
            - mariadb
            - wordpress
        volumes:
            -  ahabachi-inception-wp-volume:/var/www/wordpress
        networks:
            - ahabachi-inception-network
        restart: on-failure




    # redis:
    #     image: redis:2023.05.03
    #     container_name: redis
    #     build: ./requirements/bonus/redis
    #     env_file: .env
    #     volumes:
    #         -  ahabachi-inception-wp-volume:/var/www/wordpress
    #     networks:
    #         - inception-network
    #     restart: always
    # adminer:
    #     image: adminer:2023.05.08
    #     container_name: adminer
    #     build: ./requirements/bonus/adminer
    #     ports:
    #         - "8080:8080"
    #     depends_on:
    #         - mariadb
    #     env_file: .env
    #     networks:
    #         - inception-network
    #     restart: always
    #     volumes:
    #         -  ahabachi-inception-wp-volume:/var/www/html
    # static-website:
    #     image: static-website:2023.05.12
    #     container_name: static-website
    #     build: ./requirements/bonus/static-website
    #     ports:
    #         - "8080:8080"
    #     networks:
    #         - inception-network
    #     restart: always
    # python-server-with-ssh:
    #     image: python-server-with-ssh:2023.05.11
    #     container_name: python-server-with-ssh
    #     build: ./requirements/bonus/python-server-with-ssh
    #     ports:
    #         - "2024:2024"
    #         - "2023:2023"
    #     env_file: .env
    #     networks:
    #         - inception-network
    #     restart: always
    # ftp:
    #     image: ftp:2023.05.05
    #     container_name: ftp
    #     build: ./requirements/bonus/ftp
    #     env_file: .env
    #     volumes:
    #         -  ahabachi-inception-wp-volume:/var/www/wordpress
    #     ports:
    #         - "21:21"
    #     networks:
    #         - inception-network
    #     restart: always
